// Código generado automáticamente. No editar.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
...........................................................................
..............2............................................................
....222222....2............................................................
......22...22.2............................................................
......22....2.2............................................................
......22....2.2............................................................
......2.......2............................................................
`;
            case "image3":
            case "myImage1":return img`
. . . . f f f f f . . . . . . . 
. . . f e e e e e f . . . . . . 
. . f d d d d e e e f . . . . . 
. c d f d d f d e e f f . . . . 
. c d f d d f d e e d d f . . . 
c d e e d d d d e e b d c . . . 
c d d d d c d d e e b d c . f f 
c c c c c d d d e e f c . f e f 
. f d d d d d e e f f . . f e f 
. . f f f f f e e e e f . f e f 
. . . . f e e e e e e e f f e f 
. . . f e f f e f e e e e f f . 
. . . f e f f e f e e e e f . . 
. . . f d b f d b f f e f . . . 
. . . f d d c d d b b d f . . . 
. . . . f f f f f f f f f . . . 
`;
            case "KPWmU#+*^GE@;_T9,Lf6":
            case "Cabezo Soler":return img`
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd1ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbdddbbdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbcccfccccceeccbddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbffccccccccceecceebdbddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbfcccccccccccccceeeeeeeecccdddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbfccccccccccccccccccceeeeeecceebbddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbcfccccccccccccccccccccccceeccceeefcdddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcfcccccccccccccccccccccccceeeccceeeeccddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbffccccccccccccccccccccccccceeeecceeeeeeebddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbffccccccccccccccccccccccccccceeeecccceeeeeeebddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbfffccccccccccccccccccccccccceeeeeeeeccccceeeeeeefbddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbcfccccccccccccccccccccccccccceebeeeeeccccfeeeeeeeeebdddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcfcccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeebdddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcccccccccccccccccccccccccccccccceeeeebeebeebbeeeeeeeeeeeeebddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddbcccccccccccccccccccccccccccccccccceeeeeeeeeebeeeeeebbeebeeeeebddddddddddddddddddddddddddddddddddddddddd
bbbbbbbddddbbddbbbbdddddddddddddddddddddddddddddddddddbffcccccccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeebddddddddddddddddddddddddddddddddddddddd
bbbbbbbbbbbbbbbbbbbbbdddbddbdddddddddddddddddddddddddbfcccccccccccccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeebdddddddddddddddddddddddddddddddddddddd
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddddbbbcfcccccccccccccccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeebddddddddddddddddddddddddddddddddddddd
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfcccccccccccccccccccccccccccccccccccccccceeeccceeeeeeeeeeeeeeeeeeeeeeeeeeeebddddddddddddddddddddbdddddddddddddd
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbcccccccccccccccccccccccccccccccccccccccccceeecceeeceeeeeeeeeeeeeeeeeeeeeeeeeeebbdbbdddddbbbbbbbbdbdddddddddddddd
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbfffccccccccccfcccccccccccccccccccccccccccccccceecceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbdbbbbbbbbbbbbbbbbbbbbbbbdddbdd
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfcccccccccccccccccccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbdbbbbbbbbbbbbbbbbddddddddddd
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccceeeeeeeeeeeccceeeeeeeeeeeeeeeeeeeeeeeeeeccbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbcbcbbccbbbccccccffccccccccccccccccccccccccfcccccccccccccccccccccccceeeeeeeeeeecceeeeeeeceeeeeeeeeeeeeeeeeeeeeeebbbbbbbccccccccccbcccbbbbc
bbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccceeccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbbbbbbbbbbccbcccb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccecceeccceeeeceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbbbbbbbbbbbbcccc
cbccccccccbcbbbbcccccbbbbbbbcccfffcccccccccccccccccccccccccccccccccccffcccccccccccccccccceeeceeeeeeccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccccccccccbbbbbccc
cccccbbbbbbbbbbcbcccccccffcfccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccceeeeceeeeeeceeeeeeeeeeeeeeeeeeeeeeeeecccceeeeeeeeeeeeccbbbccccccccccccc
cbccccbbbbbbcbbcccccccccccccccccccccccccccffccfcfcccccccccccfffccccccccccccccccccccccccccceeeceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeccebeeeeeeeeeeeeeccccccccccccccc
cccccbcccccccffcfffcccccccccccccccccccccccccccfcccccccccccccccccccccccccccccccccccccccecccceeceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecceeeeeeeeeeeeeeccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccceeccccccccccccccceeccccceeeeeeeeeeeeeeeeeeeceeeeeeeeeccccceeeeeeccceeeeeeeeeeeeeecccccbcccc
ccccccccccccccccccccccccccccccccccccccccccfcccfcccfffffcccccccccccccceeeeeecccceecccfcceecfcccceeeeeeeeeeeeeeeeccceeeeeccccccceeeeeeeecceeeeeeeeeeeeeeeecccccccc
cccccccccccccccccccccccccccfcccfcccccccccccccfffcccccccccccccccccccccceebeebeecccccccfceeeecccceecccceeeeceeeeeeceeeeeeeeccccceeeeeeeeeceeeeeeeeeeeeeeeeeeeeeecc
ccccccccccccccccccccccccccccfffccccccfffcccccccccccccccccfccccccccccccbbbebbebeeccccccceeeeeccceefcccceecceeeecceeeeeeccceeecceecceeeeeceeeeeeeeeeeeeeeeeeeeeeee
cccccccccccccccccccccccccccccccccfcccfcccccffcccccccccccccccccccccccccceebbeebbeeeeeeeeeeeeeeceeecccccccccceeeeeeeeeccccceeecceeccfcceeeeeecceeeeeeeeeeeeeeeeeee
cccccccccccccccccccccccccccccccccccccccfffffffcccfccccccccccffcccccccceeebbeebbeeebeeeeeeeeeeeeeeeeccccccccccecceeeeeccccceeecceeeeeeeeeeeeeeeeeeceeeeeeeeeeeeee
ffccfffccccccccccfccccccfcccccfccffccffffccccfcccccffcccfcfcccffcccccceeeccceebeeebeeeeeeeeeeeeeebeeecceeecccccccceeeecccceeeeeeeeeebeeceeeeeeeecceeeeeeeeceeeee
ccccccccccfffcccccccccccccfccccffffccccccccccccccccccccccfcccffffccccceecccceeeeeeebefeeeeeeeeeeeeeeeeeeecccccccceeeececeeeeeeeeefeeeeecceeeeeeeeceeeeeeeeeeeeee
ccccccccffcccccccccccccccfccccfffccccccccccccfccccccfcccfcccfccccccccceecceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecffccccceeeeeeeeeeeeeeebeeeeeeeeeeeeeeeeeeeeebeeeeeeeee
ccccccccfcccccccccccccccccfffffcccccfccfffffcccccccccccfcccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
ccccffccccccccccccccfffcccccccccfccccfffffccccccccfccfffccccffcccccccccccccceebeeeeeeeeeebeeeeeeeeeeeeeeeecceeeccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
ccccccccccffccccccccfffccffffccccccfffcffccccfcccfcffccffcfffcccccccccccfffcceeeeceeeeeeeeebbeeeeeeeeeeeeeceeeeeceeeeeeebeeeeeeeeeeeeeeeeeeeeeeeceeeeeeeeeeeeeee
cffcccfcffccccccccccccccffcffcfffffffccfffcffccccccccccfffcccfcccccccccccccccceeeeeccceeeeeeeeeeeeccceeeeceeeeeeeeeeeeeebeeeeeeeeeeeeeeeeeeeeeccccccccceeeeeeeee
cccccfffffcccccffccccfcfffffffffffffcccffcffccccccffffffcccccccccccccceecccccceeeeeecceeeeeeeeeeeccfccceeeeeeeeeeefeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccceeeeeeee
ccccccfffcccccfcccccccccccfcffccccccccccccfccccccfcffcccfffcccccccccccceeccccccceeeecceeeeeeeeeeeecfcccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeccceeeeecc
fccccccccffccfccfcffffffccccffcccfccccccffcfcccffcfcfccfffcccccccccccccceecccccccceeeeeceeeeeeeeeeeccccccceeeeeeeeeeeeeeeeeeeeeeeeeeecceeeeeeeeceeeceecccceeeece
cccccffccfccfffffffccfccccccccccccffcfccfcfccffffcffcccccfccccccccccccccccceccccccceeeeeeeeeeeeeeeeeeeecccceeeeeeeeeeeeeeeeeeeeeeeeeeeccceeeeeeeeeeeeeccceeeeeee
ffccfffffffffffffffccfccccccccfcccccfcfffffcccffffcccfccffccccccccfccccccccceeccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccceeeeeeeeeeeccfceeeeee
fffffffffffffffffffffffcccffccffffcccfcccccccccccccccccccccccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeebccceeeeeeeeeeeeeeeeeeeeeeeeecccceeeeeeeeecccceeeeee
ccfffffffffffffffffffffccfffffffffffffccccccccccccccfccccccccccccccccccccccccccccccccccccccccccceccecceeeeccccccccceeeeecceeeeeeeceeeeeeeecccceeeeeeeecccccecccc
ffffffffffffffffffffcffffffffcffffcffcccccccfcccffffffccccccccccccccccccccccccccccffcfffcccccfcccfcccccccefccccccccccccccccecceeeccceeeceeeccccceeeeeccccccccccc
ffffffffffffffffffffffffffffffffffffcfffffffcccffffcccccfccffffccccfffccfffccffcccccccccccccccccccccccccceeccccfcccccccccccccceeeeffcccceecccccccccccccceccecccc
fffffffffffffcfcfffffffffffffcffffffffcffccfcfffffcccccfffccccfcfffffcccffccfccccffcccccfccccccccccccfffcccceeccccccccffcfcccccceeccccccccfffcffcccccccceeeecccc
fffffffffffffffcffffffffcfccffffffcffccffccccfcfcffffccccfccfccfffcffcccfccfcccccfccfccfffcccccccccccfffffceefcccccccffffccccfccceeccfffcccccccccccccccceeeeeecf
ffffcffffccfffffffffffcfcccffffffffffffccccffffcccffceecfccfffffcccfcccccceccccccccccccccfffcffccccccffffceeeccccccccffccecccffccceeecffccccccccccccccceeeeeeccc
ccffcccffffffffffffffccffcffccffffffcfccccfffcffccccceecccccccfccccffffcfccccfccccccccccccfffffcccfcccffffccccffffffcfccccccffffccceeccfcccffcfccccccceeeeeeccfc
fcfccccffffffffffffffffcfffcfffffffccfcccfffccccccccceeeeeccccfccfffffffffcffffccecffceeeeccfcceecccfffcfffffffffffffffffccfffffffcccfcffcfffffcccceeefeeeeeeecf
fcceeecfffffffffffffffffffffffffffccccccfccccecccccceeeeeeeeeffcffffffffffcfffffeeeecceeeeeeeceeeccccffcccfffffffffcffffcfcfffcfffffffffffffffffffceecceeeeeeeee
ccceeeecccccccccfcfcffffccccffffcfcccfffffcceeeccccceeeeeeeeeeccfffffffcfcfffccfeeeeeceeeeeeeeeecffccffcffcffffffffcccffffccfcccfffffffccfffffffccfeefffceeeeeee
fffeeeeeeeccccccccccfffcffcffcfffcfffceeefccffcccccceeeeeeeeeeecfffffccfffffffcceeeeeeecceeeeeeeecfffffffffffffffffffffffccfffcccccfffffffffffccccfcecfffcccceee
cffeeeeeeeeefcfffffccfcccfcffcfcffccceeeeeeeeffffffffcccfeeeeeeccffccccecccccffcccceeeeccccceeeefecffffccfffffffcccffccffccfffffccccccffffffffcfcfffccfffccfccee
eeeeeeeeeeeeecffffffccccccccccceccceeeeeeeeeeeeefccffccccfceeeeccceeeeeeeecccccccfceeefccffffccffeccffffffffffffccfffccfcccccffffcccfccffffcccfffffffccffccffccc
eeeeeefeeeeeecfccccceeeeccccccceeeeeeecceceeeeeeccfffffcccccccccccceeccceecccccccfccecffffffffffcfcfcfccffcccccccccccccfcfccccffffffffffffcccefffffffffffffffccc
eeeecffffffffffcccccfcfffccccfccceeeeefffffffffffffffffffffffffffffccfffeefcccfffffccccfffffccfffffcccecfcccccccccccffcffccffffcfffffffffffcfcffffffffffffffffcc
eeeeffcfccffffffcfffffffffffcccffeeeeefffffffcffffccfffffffffffffccffffceefcffffffffffffffffcccffffcceeeccccccccccffffffffffffccfccffffffffffcffffffffffffffffcf
eeeeccfeecffffffccffffffffffffccfeeeeecffffffffcfccffffffcffffffccccfccceeccccffcccffffffcffcccfccfccccccccccccccccfccfccfccfffcceefffffffffffffffffffffffffffcf
eeeecffeeffffcffffffffffffffffccfffcecfffffffcccffffffffffffffffffccfccccccccccfccccffffffffffffffffffffffcccccccccfccceeeeccffffcecffffffffffffccccccccfffffffc
eeeeffeeeffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffcccffcccfccfccccfcfffffffffffffffffffffffccccfffcccfcffcffffffccccffffffffffccceeeeeefffffcc
ceefffcecfffffffffffffffffffffffffffffffffffffffffffffffccfccfffffffffffffffffccfcfffffffffffffffffffffffffffffffffffffffffffffffcffccfffffffffffffcceeeeecfcfcc
fffffffccccffffffffffffffffffffffffffffffffffffffffffffccccccccccccffffffffffffffffcffffffffffffffffffcfffcffffffffffffffffffffffcfffcccfffffffffffffffceececfcf
ffffffffffccffffffffcccccfffffffffffffffffffffccccccccfcccccccccffffffffffffffffffffffffffffffffffffcfcfcccfffffffffffffffffffffffffffffffffffffffccfffccfeffccf
fffffffffffffcccccccccccfffffffffffffffffffccccccccccccccccccccccfffffffffffffffffffcffffffffffffffffccccccfffffffffffffffffffffffffffffffffffffffcecffceeefcfff
ffffffffffffcccccccccccccccccfffffffffccffcccccccccccccccccccccccccfffffffffffffffffcfffffffffffffffcffcccfffffffffffffffffffffffffffffffffffffffffeeeeeeeeeeeff
ccccccccccccccccecccccccbccccfffccccffcccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffccfffffffffffffffffffffcffffffffffffffffffffffceeeeeeeeeeecf
cccccccccccccccceeccccccccccccccccccffccbbccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffccecfeeeeeeeff
ccccccccccccccfceeeccccccccccccccccccfcccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffccffffffffffffffcffffffffffffffffffffffcccfeeeeefff
cccccccccccccfcfceccccccccccccccccccccccccccccccccecccccccccccccccccfffffffffffffffffffffffffcfffffffffcffffccccccccccccfffffffffffffffffccfcfffffffffffceefffff
cccccccccccfccffccfcccccccccccccccccccccccccceeeccecccccccccccccccccccccccccccccccccccccccccccccccccffccfffccccccccccccccccfccccccfffffccccccffffffffffffcffcffc
cccccccccccffcfffffcccccccccccccccccccbbbcccceeeeeeeccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccccccccccccccccccccccccfcfffcffffffffffffffffffcf
cccccccccccccfcccccccccccccccccccccccccbbcccceeeeeeeccceccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffffffffffffffffffffff
ccccccccccccfffcccccccccccccccccccccccccccccceeeeeeeccceeeecccccccccccccccccccccccccccccccccccccccecccccccccccccccccccccccccccccccccccccfffffccfffffffffffffffff
ccccccccccccccccccccccccccccccccccccccccccccceeeeeecccfeeeeeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffccccccccccccccccccccffffffffffcff
cccccccccccccccccccccccccccccccccccccccccccceeeeeeeccffceeeeeebbbbbbbbcccccccccccccccccccccccceccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccffeeccccfeeeeeebbbbbbbbbbbbbbbbbbbbbbbbccccccbbbbbecccccccebbbccccccbcccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccbcccfffceecffceeeeeeccebbbbbbbbbbbbbbbbbbbbbcccccccebeecbeeeeebbbbbbbcccbbbbbbcccccccccccccccccccbbbccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccffffffeefffcffeeeeccbbbbbccccbbbbeebbeeebcccccccccccccceeebbeebbbbbbbebbbbebbbccccccccccccccbbbbbbbbbbbbbbbbccbbbbc
cccccccccccccccccccccccccccccccccccccccbbbbccfffffceecfffffceeeccbbcbbbbcccceeeeeeeeeccccbcceeecccccceeeeeeeeecebbebbbbbbbeccbccccccccccbbbbbbbbbbbbbbbbbebbcccc
cccccccccccccccfcccccccccccccccccccccccccccccfffffcffffffffffffccccccccccccccceeecffeeccebeeebeeeccccceebeeccccceeeeebbbbbbbbbbbbbbbbcccceeeebbeebbebbbbbccccccc
cccccccccccccccfcccccccccccccccccccccccccccccffffffffffffffffcfffcccccccccccccffffffeecceeeebbbbeeeccceeeeeccccbeeeeeeebbbbcbbbbbbbbbbbbeebeeeeeeeeebebccbbbcccc
cccccccccccccccfccccccccccccccccccccccccccccffffffffffffffffffffcccccbbcccccccffffffcfffeeeeebbbeeeecceeeeccccceeeeeeeebbbeecceeeeebbbecbbbbbbeeeeeeeeebbbebeeee
cccccffccccecccccccccccccccccccccccccccccccffffffffffffffffffffccccccccccccfccffffffcffffceeeeeceeeeeeeeeccccceeeeeeeeeeeeeebbeeeeeebeeeeeeeeeeeeeeeebbbbbccceee
bccccffccceecccccccccccccccccccccccccccccfffffffffffffffffffffffcfccccccfcffccffffffffcffcfceccccceeeecccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebebbcccceee
bcccfcfccceeccfccccccccccccccccccccccccccfffffffffffffffffffffffcfffcccfffffffffffffffffcffcccccccceeccccccceeeeecceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccccccccce
cccccfffccccfffcccccccccccccccccccccfccccfffffffffffffffffffffffffffcccffffffffffffffffffffffccfffceecccccccceeecccceeecccceeeeeeeeeeeeeeeeeeeeeeeeeecccccccccee
cccccfffffffffccccccccffccccccccccffffffffffffffffffffffffffffffffcfffcfffffffffffffffffffffffffffccecfccfcccccccffcccccffcceeccceeecccffceeeeeeeeeeccccccccccee
`;
            case "w+FRAj3?F686D-F91,C#":
            case "la encantá":return img`
............................................................
............................................................
........................eeeeeeeeeeee........................
.......................eeeeeeeeeeeeeeeeeeee.................
.....................eeeeeeeeeeeeeeeeeeeeee.................
....................eeeeeeeeeeeeeeeeeeeeeeee................
....................eeeeeeeeeeeeeeeeeeeeeeeee...............
..................eeeeeeeeeeeeeeeeeeeeeeeeeee...............
..................eeeeeeeeeeeeeeeeeeeeeeeeeee...............
.................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
.................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............
...............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee............
...............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee............
..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........
..............eeeeeeeeeeeeeeeeeeeee2eeeeeeeeeeeee...........
..............eeeeeeeeeeeeeee22eee22beeeeeeeeeeee...........
..............eeeeeeeeeeeeeee22ee2222eeee2eeeeeee...........
..............eeeeeeeeeee2eee22ee22222eee2eeeeeee...........
..............eeeeeeeeeee2eeee222eb222eeeeeeeeee............
..............eeeeeeeeee222eee22222222222eeeeeee............
..............eeeeeeeee2d22222222222b22222eeeeeee...........
.............eee222eeeedf22f2f2222222f22f2eeeeeee...........
.............eee2222eeed2ffff2222222ffff22eeeeeee...........
.............ee22222eeedffe11f22222fe11ff2eeeeeee...........
.............eee2222eeedb2aaad22222daaa222beeeee............
.............eee2222eeebb22bb2222222222bbbbeeeee............
.............eeee11eeeebbbbbb22222222bbbbbeeeeee............
.............eee111eeeebbbbbb22bbbb222bbbbbeeeee............
.............eeee11eeee2222222bbbb22222222eeeeee............
.............eeeee1eeeee222222bbbb22222222eeeeee............
.............eeeeeeeeeee2222222bbbb22222222eeeee............
..............eeeeeeeeeee2222222bb222222222eeeee............
.............eeeeeeeeeee22222222bd42222222eeeeee............
.............eeeeeeeeee22222222223222222b2eeeeee............
.............eeeeeeeeeee2222222222222222b2eeeee.............
.............eeeeeeeeeee222222222222222222eeeee.............
.............eeeeeeeeeee2222222222222222e2eeeee.............
............eeeeeeeeeee22222222222222222eeeeeee.............
.............eeeeeeeeee22222222222222222eeeeeeee............
.............eeeeeeeeee22222223333332222eeeeeeee............
.............eeeeeeeeee2222222377732222b4eeeeee.............
.............eeeeeeeee222222223333322d244eeeeee.............
.............eeeeeeee44222222223333222b4aaeeeeee............
.............eeeeeeeee42b222222222222b44aeeeeeee............
............eeeeeeeeeea442222222222224aaaeeeeeeee...........
............eeeeeeeeeeeaa42b222222244aaaaeeeeeeee...........
............eeeeeeeeeeeaaa44422224444aaaaeeeeeeee...........
............eeeeeeeeeeeaaaa4444444444aaaaeeeeeeee...........
............eeeeeeeeeeeaaaa4444444444aaaaeeeeeeeee..........
...........eeeeeeeeeeeeaaaa4224444b24aaaaeeeeeee44..........
...........eeeeeeeeeeeeaaaa422222222444aaeeeeeee444.........
..........eeeeee444eeeeaaaa4222222222224aaeeeee422444.......
..........ee44444224eeeaa44222222222222444eeee82222224......
..........e44222222244a444b2222222222222244448822222244.....
.........e4422222222288422222222222222222222288222222244....
.........442222222222888822222222222222222222822222222244...
........4422222222228888b22222222222222222228822222222222...
........42222222222881182222222222222222222288822222222224..
.......b222222222228111882222222222222222228118222222222244.
......42222222222281111118822222222222222281118222222222224.
.....4222222222228111111111822222222222228111182222222222244
....44222222222281111111111888222222288881111188222222222222
...442222222222471111111111118888888811111111118442222222222
..4422222222224ee8111111111111111111111111111118442222222222
..422222222224eee8111111111111111111111111111118444222222222
.442222222224eeee8111111111111111111111111111118844422222222
4422222222244eeee81111111111111111111111111111118e4442222222
222222222224eeeee81111111111111111111111111111118eee44422222
22222222244eeeeee81111111111111111111111111111118eeeee442222
bb22222224eeeeeee81111111111111111111111111111118eeeeee42222
..2222244eeeeeeee8111111111111111111111111111188eeeeeee44422
.2222224eeeeeeeeee87111111111111111111111111118eeeeeeeeee4..
.22.b24eeeeeeeeeeee8111111111111111111111111118eeeeeee......
....b44.eeeeeeeeeee8111111111111111111111111118eeeeeee......
....4.....eeeeee..e8111111111111111111111111118eeeeee.......
...................8111111111111111111111111118eeee.........
...................8111111111111111111111111118eee..........
...................8111111111111111111111111118.............
...................8111111111111111111111111118.............
..................88.11111111111111111111111118.............
..................11111111111111111111111111118.............
.................81.11111111111111111111111111..............
.................88111111111111111111111111111..............
...................1111111111111111111111111111.............
...................1111111111111111111111111111.............
.....................1111111111111111111111111..............
.......................11111111111111111111111..............
.........................11111111111111111111...............
.................................1111111111.................
`;
            case "image2":
            case "myImage0":return img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`;
            case "image4":
            case "myImage2":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "comecocos septimo intento":
            case "anim6":return [img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..........fffffff.............
.........f5555555f............
........f551555555f...........
.......f555f5555555f..........
.......f55555555555f..........
.......f51515555555f..........
.......f15155555955f..........
.......f55559959555f..........
.......f55555955995f..........
.......f55555959595f..........
........f995999559f...........
.........f55955959............
..........ff99f9f9............
.............9................
..............................
..............................
..............................
..............................
..............................
..............................
`, img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..........fffffff.............
.........f5555555f............
........f551555555f...........
........1f5f5555555f..........
.........1f55555555f..........
..........1f5555555f..........
...........f5555955f..........
..........1f9959555f..........
.........1f55955995f..........
........1f555959595f..........
........f555999559f...........
.........f55955959............
..........ff99f9f9............
.............9................
..............................
..............................
..............................
..............................
..............................
..............................
`];
            case "comecocos septimo intento0":
            case "anim7":return [img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..........fffffff.............
.........f5555555f............
........f551555555f...........
.......f555f5555555f..........
.......f55555555555f..........
.......f51515555555f..........
.......f15155555955f..........
.......f55559959555f..........
.......f55555955995f..........
.......f55555959595f..........
........f995999559f...........
.........f55955959............
..........ff99f9f9............
.............9................
..............................
..............................
..............................
..............................
..............................
..............................
`, img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..........fffffff.............
.........f5555555f............
........f551555555f...........
........1f5f5555555f..........
.........1f55555555f..........
..........1f5555555f..........
...........f5555955f..........
..........1f9959555f..........
.........1f55955995f..........
........1f555959595f..........
........f555999559f...........
.........f55955959............
..........ff99f9f9............
.............9................
..............................
..............................
..............................
..............................
..............................
..............................
`];
            case "comecocos septimo intento1":
            case "anim8":return [img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..........fffffff.............
.........f5555555f............
........f551555555f...........
.......f555f5555555f..........
.......f55555555555f..........
.......f51515555555f..........
.......f15155555955f..........
.......f55559959555f..........
.......f55555955995f..........
.......f55555959595f..........
........f995999559f...........
.........f55955959............
..........ff99f9f9............
.............9................
..............................
..............................
..............................
..............................
..............................
..............................
`, img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..........fffffff.............
.........f5555555f............
........f551555555f...........
........1f5f5555555f..........
.........1f55555555f..........
..........1f5555555f..........
...........f5555955f..........
..........1f9959555f..........
.........1f55955995f..........
........1f555959595f..........
........f555999559f...........
.........f55955959............
..........ff99f9f9............
.............9................
..............................
..............................
..............................
..............................
..............................
..............................
`];
            case "myAnim3":
            case "anim5":return [img`
........................
........................
...........cc...........
...........cccc.........
.......cc...ccccccc.....
.......cccccc555555cc...
........ccb5555555555c..
.....cc..b555555555555c.
.....cccb555555ff955555c
.....ccb55555555ff55d55c
......b5555555555555555c
...c..b555d55555bb13bbc.
...cccd55ddddd55bb3335c.
....cbdddddddddd55b335c.
..cccdddddb55bdddd5555c.
..cccdddddb555bbbbcccc..
...ccddddddb5555cbcdc...
ccccbdddddddcb55cbcc....
cddddddddd55dbccbbc.....
cbdddddddd555dbbbcc.....
.ccbdddbbdd555bbcdbcc...
...cccbbbbdd55ccdddbc...
......cccbdddbccccccc...
........cdd555dc........
`, img`
........................
........................
...........ccc..........
...........cccc.........
.......ccc..ccccccc.....
.......cccccc555555cc...
........ccb5555555555c..
.....cc..b555555555555c.
.....cccb555555ff955555c
......cb55555555ff55d55c
......b5555555555555555c
...cc.b555dd5555bb13bbc.
...cccd55ddddd555b3335c.
.....bdddddddddd55b335c.
..cccdddddb55bbddd5555c.
..cccdddddb555bbbbcccc..
...ccddddddb5555cbcdc...
ccccbdddddd5cb55cbcc....
cddddddddd5555ccbbc.....
.cddddddbdd555bbbcc.....
..ccdddbbbdd55cbcdc.....
....ccbbcbddddccdddcc...
......cccdd555dcccccc...
........cccccccc........
`, img`
........................
............cc..........
............ccc.........
........ccc.ccccccc.....
........ccccc555555cc...
........ccb5555555555c..
.....ccc.b55555ff95555c.
.....cccb5555555ff55555c
......cb555555555555d55c
....c.b555555555bb55555c
....ccb555ddd5555b13bbc.
....ccd55ddddd555b3335c.
.....cdd5ddddddd55b335c.
...c.bddddb555bbbd555c..
...ccdddddbb55555bccc...
...ccdddddddcc555bcc....
...ccddddddddbcccbcccc..
.ccbddddddd55dbbbbc55c..
ccddddddddd555dbbcc5c...
cddddddbbbdd555bbccc....
.ccddddbbbbdd55bcc......
...cccbbbbbdddbcddcc....
.....cccccdd555dcccc....
..........cccccc........
`, img`
........................
............cc..........
............ccc.........
........ccc.ccccccc.....
........ccccc555555cc...
........ccb5555555555c..
.....ccc.b55555ff95555c.
.....cccb5555555ff55555c
......cb555555555555d55c
....c.b555555555bb55555c
....ccb555ddd5555b13bbc.
....ccd55ddddd555b3335c.
.....cdd5ddddddd55b335c.
...c.bddddb555bbbd555c..
...ccdddddbb55555bccc...
...ccdddddddcc555bcc....
.ccccdddddddddcccbcccc..
.cdcdddddddd55dbbbc55c..
.cdddddddddd555dccc5c...
.cbddddbbbbdd5d555cc....
..cbdddbbbbbdd5555......
...cccbbbbbbd5555c......
.....cccccccc555c.......
.............ccc........
`, img`
........................
............cc..........
............ccc.........
........ccc.ccccccc.....
........ccccc555555cc...
........ccb5555555555c..
.....ccc.b55555ff95555c.
.....cccb5555555ff55555c
......cb555555555555d55c
....c.b555555555bb55555c
....ccb555ddd5555b13bbc.
....ccd55ddddd555b3335c.
.....cdd5ddddddd55b335c.
...c.bddddb555bbbd555c..
...ccdddddb555555bccc...
..cccddddddcc5555bcc....
.cdccddddddddbcccbcccc..
.cddbdddddddddbbbbc55c..
.cdddddddddd55dbbbc5c...
.cbddddbbbbd55ddbccc....
..cbdddbbbbd555dccc.....
...cccbbbbbbddd555c.....
.....ccccccbd55555c.....
...........cc5555c......
`];
            case "myAnim5":
            case "anim10":return [img`
. . . . . . . . . . . . . . . . 
. . . . c c c c . . . . . . . . 
. . c c 5 5 5 5 c c . . . . . . 
. c 5 5 5 5 5 5 5 5 c . . . . . 
c 5 5 5 5 5 9 f 5 5 5 c . . . . 
c 5 5 5 5 5 f f 5 5 5 5 c . . . 
c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
c c b b 1 b 5 5 5 5 5 5 d c . . 
c 5 3 3 3 5 5 5 5 5 d d d c . . 
. b 5 5 5 5 5 5 5 5 d d d c . . 
. . c b b c 5 5 b d d d d c c . 
. c b b c 5 5 b b d d d d c d c 
. c c c c c c d d d d d d d d c 
. . . c c c c d 5 5 b d d d c . 
. . c c c c c b 5 5 b c c c . . 
. . c b b b c d 5 5 b c . . . . 
`, img`
. . . . c c c c c . . . . . . . 
. . c c 5 5 5 5 5 c . . . . . . 
. c 5 5 5 5 9 f 5 5 c . . . . . 
c 5 5 5 5 5 f f 5 5 5 c . . . . 
c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
c c b b 1 b 5 5 5 5 5 5 c . . . 
c 5 3 3 3 5 5 5 5 5 5 5 d c . . 
c 5 3 3 3 5 5 5 5 5 d d d c . . 
. c 5 5 5 5 b 5 5 5 d d d c . . 
. . c b b c 5 5 b d d d d c . . 
. c b b c 5 5 b b d d d d c c c 
. c c c c c c d d d d d d d d c 
. . . . c c c b 5 5 b d d d c . 
. . . . . c d 5 5 b b c c c . . 
. . . . c c c c c c c . . . . . 
. . . . c b b b c . . . . . . . 
`, img`
. . . . c c c c c . . . . . . . 
. . c c 5 5 5 5 5 c . . . . . . 
. c 5 5 5 5 9 f 5 5 c . . . . . 
c 5 5 5 5 5 f f 5 5 5 c . . . . 
c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
c c b b 1 b 5 5 5 5 5 5 c . . . 
c 5 3 3 3 5 5 5 5 5 5 5 d c . . 
c 5 5 5 5 5 5 5 5 5 d d d c . . 
. c 5 5 5 5 b 5 5 5 d d d c . . 
. . c b b c 5 5 b d d d d c . . 
. c b b c 5 5 b b d d d d c c c 
. c c c c c c d d d d d d d d c 
. . . . c c b 5 5 b d d d c c . 
. . . . c d 5 5 b b c c c . . . 
. . . . c c c c c c c . . . . . 
. . . . c b b b c . . . . . . . 
`, img`
. . . . c c c c c . . . . . . . 
. . c c 5 5 5 5 5 c . . . . . . 
. c 5 5 5 5 9 f 5 5 c . . . . . 
c 5 5 5 5 5 f f 5 5 5 c . . . . 
c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
c c b b 1 b 5 5 5 5 5 5 c . . . 
c 5 3 3 3 5 5 5 5 5 5 5 d c . . 
c 5 5 5 5 5 5 5 5 5 d d d c . . 
. c 5 5 5 5 b 5 5 5 d d d c . . 
. . c b b c 5 5 b d d d d c . . 
. c b b c 5 5 b b d d d d c c . 
. c c c c c b b d d d d d d c c 
. . . c c 5 5 b 5 5 d d d d d c 
. . . . c b 5 5 b b c c c c c c 
. . . . c c c c c c . . . . . . 
. . . . . c b b b c . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . c c c c . . . . . . . . 
. . c c 5 5 5 5 c c . . . . . . 
. c 5 5 5 5 5 5 5 5 c . . . . . 
c 5 5 5 5 5 9 f 5 5 5 c . . . . 
c 5 5 5 5 5 f f 5 5 5 5 c . . . 
c c b b 1 b 5 5 5 5 5 5 c . . . 
c c 3 3 b b 5 5 5 5 5 5 d c . . 
c 5 3 3 3 5 5 5 5 5 d d d c . . 
. b 5 5 5 5 5 5 5 5 d d d c . . 
. . c b b c 5 5 b d d d d c . . 
. c b b c 5 5 b b d d d d c c c 
. c c c c c c d d d d d d d d c 
. . . c c c c d 5 5 b d d d c c 
. . . c b c c b 5 5 b c c c . . 
. . . c c c d 5 5 b c . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . c c c c . . . . . . . . 
. . c c 5 5 5 5 c c . . . . . . 
. c 5 5 5 5 5 5 5 5 c . . . . . 
c 5 5 5 5 5 9 f 5 5 5 c . . . . 
c 5 5 5 5 5 f f 5 5 5 5 c . . . 
c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
c c b b 1 b 5 5 5 5 5 5 d c . . 
c 5 3 3 3 5 5 5 5 5 d d d c . . 
. b 5 5 5 5 5 5 5 5 d d d c . . 
. . c b b c 5 5 b d d d d c . . 
. c b b c 5 5 b b d d d d c c c 
. c c c c c c d d d d d d d d c 
. . . c c c c d 5 5 b d d c c . 
. . c b b c c c 5 5 b c c . . . 
. . c c c c c d 5 5 c . . . . . 
`];
            case "myAnim7":
            case "anim12":return [img`
................................................................................
................................................................................
................................................................................
................................................................................
..................ff............................................................
.................fff............................................................
................fffffff.........................................................
...............fffff3ff.........................................................
..............ff3f333f..........................................................
...............fff333f..........................................................
.............ffffff3fffff.......................................................
............ff333333ff33ff......................................................
...........ff333333faf333f......................................................
...........f33333ffaaf333ff.....................................................
...........f3fffff99af3333ff....................................................
..........ff3faaa999ff33333ff...................................................
.........ff33ffaa999f3333333ff..................................................
.......fff3333faaaaff33333333ff..fff............................................
......ff333333fffff33333333333ffffffffff........................................
......f33338333333333333333333333333333f........................................
......f8a8833333333333333333333333333333ff......................................
......ffaaa333333333333333333333333333333ffff...................................
........fffff33333333333333333333333333333333f..................................
...........ffff333333333333333333333333333333fff................................
..............f33333333333333333333333333333333ff...............................
...............ff3333333333333333333333333333333ff..............................
................f33333333333333333333333333333333f..............................
.................f33333333333333333333333333fff33ff.............................
...............ffff333333333333333333333333ff.ff33f.............................
..............fff3f3333333333333333333333333f..ff3f.............................
.............ff333f33ffff3333333333333333333ff..fff.............................
.............f33333333f.ffff33333333333333333f...ffff...........................
.............f333f3333f....fff33fff3333333333f..ff33f...........................
.............f333f3333f......ffff..ffff33333ff..f.fff...........................
.............f333ff33ff...............fff3333f..fff.............................
............f333f.f33ff................ff3f33ffff...............................
............f333f.f333f.................f33f3ff33f..............................
............f33ff.f33ff.................f33f33333fff............................
............f33f.f333f..................fff.ff333333ff..........................
...........ff33f.ff3ff..................ffff..ffff333f..........................
..........f3333ffff3f....................f3f......ffffff........................
.........f33333ff333f....................f3ff........ff.........................
.........f3333ff333ff....................ff3ff..................................
.........f3333f3333f......................fffff.................................
..........fffffffff.........................fff.................................
...........fffff............................ffff................................
............f...................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
`, img`
................................................................................
................................................................................
................................................................................
................................................................................
..................ff............................................................
.................fff............................................................
................fffffff.........................................................
...............fffff3ff.........................................................
..............ff3f333f..........................................................
...............fff333f..........................................................
.............ffffff3fffff.......................................................
............ff333333ff33ff......................................................
...........ff333333faf333f......................................................
...........f33333ffaaf333ff.....................................................
...........f3fffff99af3333ff....................................................
..........ff3faaa999ff33333ff...................................................
.........ff33ffaa999f3333333ff..................................................
.......fff3333faaaaff33333333ff..fff............................................
......ff333333fffff33333333333ffffffffff........................................
......f33338333333333333333333333333333f........................................
......f8a8833333333333333333333333333333ff......................................
......ffaaa333333333333333333333333333333ffff...................................
........fffff33333333333333333333333333333333f..................................
...........ffff333333333333333333333333333333fff................................
..............f33333333333333333333333333333333ff...............................
...............ff3333333333333333333333333333333ff..............................
................f33333333333333333333333333333333f..............................
.................f33333333333333333333333333fff33ff.............................
...............ffff333333333333333333333333ff.ff33f.............................
..............fff3f3333333333333333333333333f..ff3f.............................
.............ff333f33ffff3333333333333333333ff..fff.............................
.............f33333333f.ffff33333333333333333f...ffff...........................
.............f333f3333f....fff33fff3333333333f..ff33f...........................
.............f333f3333f......ffff..ffff33333ff..f.fff...........................
.............f333ff33ff...............fff3333f..fff.............................
............f333f.f33ff................ff3f33ffff...............................
............f333f.f333f.................f33f3ff33f..............................
............f33ff.f33ff.................f33f33333fff............................
............f33f.f333f..................fff.ff333333ff..........................
...........ff33f.ff3ff..................ffff..ffff333f..........................
..........f3333ffff3f....................f3f......ffffff........................
.........f33333ff333f....................f3ff........ff.........................
.........f3333ff333ff....................ff3ff..................................
.........f3333f3333f......................fffff.................................
..........fffffffff.........................fff.................................
...........fffff............................ffff................................
............f...................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
`];
            case "player_sprite":
            case "anim13":return [img`
..............................
..............................
..............................
..............................
..............................
.........fffff................
.........fff2f................
.........ff212................
.........f23f2eee.............
.........22222eeee............
..........244eeeee............
........22724eeeee............
........22722eeeee............
........22777eeeee............
........22777eeeeee...........
.........2227eeeeee...........
.........722221111............
.........7772211111...........
.........aaaa1111111..........
.........666111111111.........
.........66696.2..2...........
.........66696................
.........66696................
.........66696................
.........ee5aa................
.........eeeeaa...............
..............................
..............................
..............................
..............................
`, img`
..............................
..............................
..............................
..............................
..............................
.........fffff................
.........fff2f................
.........ff212................
.........f23f2eee.............
.........22222eeee............
..........244eeeee............
........22724eeeee............
........22722eeeee............
........22777eeeee............
........22777eeeeee...........
.........2227eeeeee...........
.........722221111............
.........7772211111...........
.........aaaa1111111..........
.........666111111111.........
..........666..2..2...........
..........9666................
........a999666...............
........a99..66e..............
........aaa..eee..............
..............................
..............................
..............................
..............................
..............................
`];
            case "enemy_tiburon":
            case "anim1":return [img`
.............ccfff..............
...........ccddbcf..............
..........ccddbbf...............
..........fccbbcf...............
.....fffffccccccff.........ccc..
...ffbbbbbbbcbbbbcfff....ccbbc..
..fbbbbbbbbcbcbbbbcccff.cdbbc...
ffbbbbbb99bbcbcbbbcccccfcdbbf...
fbcbbb11991bcbbbbbcccccffbbf....
fbbb11111111bbbbbcccccccbbcf....
.fb11133cc11bbbbcccccccccccf....
..fccc31c111bbbcccccbdbffbbcf...
...fc13c111cbbbfcddddcc..fbbf...
....fccc111fbdbbccdcc.....fbbf..
........ccccfcdbbcc........fff..
..........ffffffffff............
..........fff....fff............
..........eee....eee............
..........eee....eee............
........eeeee..eeeee............
........eeeee..eeeee............
........eeee2..eeee2............
........22222..22222............
................................
`, img`
.............ccfff..............
............cddbbf..............
...........cddbbf...............
..........fccbbcf............ccc
....ffffffccccccff.........ccbbc
..ffbbbbbbbbbbbbbcfff.....cdbbc.
ffbbbbbbbbbcbcbbbbcccff..cddbbf.
fbcbbbbb99bbcbcbbbcccccfffdbbf..
fbbb1111991bcbcbbbcccccccbbbcf..
.fb11111111bbbbbbcccccccccbccf..
..fccc33cc11bbbbccccccccfffbbcf.
...fc131c111bbbcccccbdbc...fbbf.
....f33c111cbbbfdddddcc.....fbbf
.....ff1111fbdbbfddcc........fff
.......cccccfbdff...............
.........fff..fff...............
.........fff..fff...............
.........eee..eee...............
.........eee..eee...............
.......eeeee.eeee...............
.......eeee2.eee2...............
.......22222.2222...............
................................
................................
`, img`
..............cfff..............
............ccddbf..............
...........cbddbff.........ccc..
..........fccbbcf.........cbbc..
...fffffffccccccff.......cdbc...
.ffcbbbbbbbbbbbbbcfff....cdbf...
fcbbbbbbbbbcbbbbbbcccff.cdbf....
fbcbbbb99bbbcbcbbbcccccffdcf....
fbb111199bbbcbcbbbccccccbbcf....
.fb11111111bbcbbbccccccccbbcf...
..fccc33cb11bbbbcccccccfffbbf...
...fc131c111bbbcccccbdbc..fbbf..
....f33c111cbbccdddddbc....fff..
.....ff1111fdbbccddbcc..........
.......cccccfdbbbfcc............
........fff...fff...............
........fff...fff...............
........eee...eee...............
........eee...eee...............
......eeeee.eeeee...............
......eeee2.eeee2...............
......22222.22222...............
................................
................................
`, img`
.............ccfff..............
............cddbbf..............
...........cddbbf...............
..........fccbbcf............ccc
....ffffffccccccff.........ccbbc
..ffbbbbbbbbbbbbbcfff.....cdbbc.
ffbbbbbbbbbcbcbbbbcccff..cddbbf.
fbcbbbbb99bbcbcbbbcccccfffdbbf..
fbbb1111991bcbcbbbcccccccbbbcf..
.fb11111111bbbbbbcccccccccbccf..
..fccc33cc11bbbbccccccccfffbbcf.
...fc131c111bbbcccccbdbc...fbbf.
....f33c111cbbbfdddddcc.....fbbf
.....ff1111fbdbbfddcc........fff
.......cccccfbdbbfc.............
........fff..fffff..............
........fff...fff...............
........eee...eee...............
........eee...eee...............
......eeeee.eeeee...............
......eeee2.eeee2...............
......22222.22222...............
................................
................................
`];
            case "enemy_calavera":
            case "anim11":return [img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f1111111df.......
......fd1111111ddf......
......fd111111dddf......
......fd111ddddddf......
......fd1dfbddddbf......
......fbddfcdbbbcf......
.......f11111bbcf.......
.......f1b1fffff........
.......fbfc111bf........
........ff1b1bff........
.........fbfbfff.f......
..........ffffffff......
............fffff.......
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
.........fffff..........
........f11111ff........
.......fb111111bf.......
.......f1111111dbf......
......fd111111dddf......
......fd11111ddddf......
......fd11dddddddf......
......f111dddddddf......
......f11fcddddddf......
.....fb1111bdddbf.......
.....f1b1bdfcfff........
.....fbfbffffffff.......
......fffffffffff.ff....
...........ffffffff.....
........f1b1bffffff.....
........fbfbffffff......
........................
........................
........................
........................
`];
            case "enemy_vampiro":
            case "anim4":return [img`
. . f f f . . . . . . . . f f f 
. f f c c . . . . . . f c b b c 
f f c c . . . . . . f c b b c . 
f c f c . . . . . . f b c c c . 
f f f c c . c c . f c b b c c . 
f f c 3 c c 3 c c f b c b b c . 
f f b 3 b c 3 b c f b c c b c . 
. c b b b b b b c b b c c c . . 
. c 1 b b b 1 b b c c c c . . . 
c b b b b b b b b b c c . . . . 
c b c b b b c b b b b f . . . . 
f b 1 f f f 1 b b b b f c . . . 
f b b b b b b b b b b f c c . . 
. f b b b b b b b b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
`, img`
. . f f f . . . . . . . . . . . 
f f f c c . . . . . . . . f f f 
f f c c . . c c . . . f c b b c 
f f c 3 c c 3 c c f f b b b c . 
f f b 3 b c 3 b c f b b c c c . 
. c b b b b b b c f b c b c c . 
. c b b b b b b c b b c b b c . 
c b 1 b b b 1 b b b c c c b c . 
c b b b b b b b b c c c c c . . 
f b c b b b c b b b b f c . . . 
f b 1 f f f 1 b b b b f c c . . 
. f b b b b b b b b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . c c . . c c . . . . . . . . 
. . c 3 c c 3 c c c . . . . . . 
. c b 3 b c 3 b c c c . . . . . 
. c b b b b b b b b f f . . . . 
c c b b b b b b b b f f . . . . 
c b 1 b b b 1 b b c f f f . . . 
c b b b b b b b b f f f f . . . 
f b c b b b c b c c b b b . . . 
f b 1 f f f 1 b f c c c c . . . 
. f b b b b b b f b b c c . . . 
c c f b b b b b c c b b c . . . 
c c c f f f f f f c c b b c . . 
. c c c . . . . . . c c c c c . 
. . c c c . . . . . . . c c c c 
. . . . . . . . . . . . . . . . 
`, img`
. f f f . . . . . . . . f f f . 
f f c . . . . . . . f c b b c . 
f c c . . . . . . f c b b c . . 
c f . . . . . . . f b c c c . . 
c f f . . . . . f f b b c c . . 
f f f c c . c c f b c b b c . . 
f f f c c c c c f b c c b c . . 
. f c 3 c c 3 b c b c c c . . . 
. c b 3 b c 3 b b c c c c . . . 
c c b b b b b b b b c c . . . . 
c b 1 b b b 1 b b b b f c . . . 
f b b b b b b b b b b f c c . . 
f b c b b b c b b b b f . . . . 
. f 1 f f f 1 b b b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
`];
            case "enemy_serpiente":
            case "anim3":return [img`
. . . . c c c c c c . . . . . . 
. . . c 6 7 7 7 7 6 c . . . . . 
. . c 7 7 7 7 7 7 7 7 c . . . . 
. c 6 7 7 7 7 7 7 7 7 6 c . . . 
. c 7 c 6 6 6 6 c 7 7 7 c . . . 
. f 7 6 f 6 6 f 6 7 7 7 f . . . 
. f 7 7 7 7 7 7 7 7 7 7 f . . . 
. . f 7 7 7 7 6 c 7 7 6 f c . . 
. . . f c c c c 7 7 6 f 7 7 c . 
. . c 7 2 7 7 7 6 c f 7 7 7 7 c 
. c 7 7 2 7 7 c f c 6 7 7 6 c c 
c 1 1 1 1 7 6 f c c 6 6 6 c . . 
f 1 1 1 1 1 6 6 c 6 6 6 6 f . . 
f 6 1 1 1 1 1 6 6 6 6 6 c f . . 
. f 6 1 1 1 1 1 1 6 6 6 f . . . 
. . c c c c c c c c c f . . . . 
`, img`
. . . c c c c c c . . . . . . . 
. . c 6 7 7 7 7 6 c . . . . . . 
. c 7 7 7 7 7 7 7 7 c . . . . . 
c 6 7 7 7 7 7 7 7 7 6 c . . . . 
c 7 c 6 6 6 6 c 7 7 7 c . . . . 
f 7 6 f 6 6 f 6 7 7 7 f . . . . 
f 7 7 7 7 7 7 7 7 7 7 f . . . . 
. f 7 7 7 7 6 c 7 7 6 f . . . . 
. . f c c c c 7 7 6 f c c c . . 
. . c 6 2 7 7 7 f c c 7 7 7 c . 
. c 6 7 7 2 7 7 c f 6 7 7 7 7 c 
. c 1 1 1 1 7 6 6 c 6 6 6 c c c 
. c 1 1 1 1 1 6 6 6 6 6 6 c . . 
. c 6 1 1 1 1 1 6 6 6 6 6 c . . 
. . c 6 1 1 1 1 1 7 6 6 c c . . 
. . . c c c c c c c c c c . . . 
`];
            case "enemy_pinguino":
            case "anim9":return [img`
. . . . . . 5 . 5 . . . . . . . 
. . . . . f 5 5 5 f . . . . . . 
. . . . f 6 2 5 5 6 f . . . . . 
. . . f 6 6 6 6 6 6 6 f . . . . 
. . . f 6 6 6 6 6 6 6 f . . . . 
. . . f 1 9 1 6 6 6 6 f . . . . 
. f f f 1 9 1 6 6 6 6 f f . . . 
f f 6 f f 3 1 1 6 6 6 f 6 f . . 
6 6 6 6 f 1 1 1 f f 6 f f . . . 
f f f f f f f 5 3 f 6 6 6 f . . 
. . . . f 5 3 3 f f f f f . . . 
. . . . f 3 3 f 1 f . . . . . . 
. . . . f 3 3 f 1 f f . . . . . 
. . . . f 3 5 f f 1 f . . . . . 
. . . . f 3 3 3 f f f . . . . . 
. . . . f f f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . 5 . 5 . . . . . . 
. . . . . . f 5 5 5 f . . . . . 
. . . . . f 6 2 5 5 6 f . . . . 
. . . . f 6 6 6 6 6 6 6 f . . . 
. . . . f 6 6 6 6 6 6 6 f . . . 
. . . . f 1 9 1 6 6 6 6 f . . . 
. . f f f 1 9 1 6 6 6 6 f f . . 
f f f 6 f 1 3 1 1 6 6 6 f 6 f . 
f 6 6 6 f f 1 1 1 f f 6 f f f . 
f f f f f f f f 5 3 f f 6 6 f . 
. . . . . f 5 3 3 f f f f f . . 
. . . . . f 3 3 5 f 1 f f . . . 
. . . . . f 3 3 f 1 1 f f . . . 
. . . . . f 3 3 3 f 1 1 f . . . 
. . . . . f f f f f f f f . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . 5 . 5 . . . . . . 
. . . . . . f 5 5 5 f . . . . . 
. . . . . f 6 2 5 5 6 f . . . . 
. . . . f 6 6 6 6 6 6 6 f . . . 
. . . . f 6 6 6 6 6 6 6 f . . . 
. f f f f 1 9 1 6 6 6 6 f . . . 
f f 6 f f 1 9 1 6 6 6 6 f f . . 
6 6 6 6 f 1 2 1 1 6 6 6 f 6 f . 
f f f f f f 1 1 1 f f 6 f f . . 
. . . . . f f f 3 3 f f 6 6 f . 
. . . . . f 5 3 3 1 1 f f f . . 
. . . . . f 3 3 3 f 1 1 f . . . 
. . . . . f 3 3 5 f f f . . . . 
. . . . . f 3 3 3 3 f . . . . . 
. . . . . f f f f f f . . . . . 
`];
            case "enemy_spider":
            case "anim2":return [img`
. . . . . . . . . . . . . . . . 
. . . . . f . . . f . . . . . . 
. . . . . f . . . f . . . . . . 
. . f . . f . . . f . . f . . . 
. . f f f f 9 f 9 f f f f . . . 
. . . . . f f f f f . . . . . . 
. . f . . f f f f f . . f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f f f f f . . . . . . 
. . f f f f f f f f f f f . . . 
. . f . . f f f f f . . f . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f . . . . f . . . . . 
. . . . . f . . . . f . . . . . 
. . . . . f . . . . f . . . . . 
. f . . . f 9 f f 9 f . . . f . 
. f f f f f f f f f f f f f f . 
. . . . . f f f f f f . . . . . 
. f . . . f f f f f f . . . f . 
. f f f f f f f f f f f f f f . 
. . . . . f f f f f f . . . . . 
. f f f f f f f f f f f f f f . 
. f . . . f f f f f f . . . f . 
. . . . . . . 1 . . . . . . . . 
. . . . . . . 1 1 . . . . . . . 
. . . . . . . 1 . . . . . . . . 
. . . . . 1 1 1 1 . . . . . . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "song1":
            case "mySong":return hex`00780004080200`;
        }
        return null;
    })

}
// Código generado automáticamente. No editar.
